/**
 * Popup quiz — types.
 *
 * This is the perpetual-study popup quiz that will eventually be
 * generated by NVIDIA from the user's real study data. It is
 * deliberately a separate surface from `QuizSession` / `QuizQuestion`
 * (the existing pre-generated pack-opening quiz) so we can evolve the
 * generator and persistence without disturbing that flow.
 *
 * Scope of this file: shapes only. No IO, no LLM, no persistence.
 */

import type {
  DictionaryDirection,
  DictionaryEntry,
} from "../../dictionary/types";
import type { AnalysisLine } from "../../analysis/types";

// ---------------------------------------------------------------------------
// Study context — read-only snapshot of what the user is learning.
// ---------------------------------------------------------------------------

/**
 * A single dictionary entry the user has been working with. Re-uses the
 * canonical DictionaryEntry shape so the generator sees full metadata
 * (meaning, reading, romaji, kanji, contextMeanings, etc.) without a
 * second lookup.
 */
export interface StudyDictionaryPick {
  entry: DictionaryEntry;
  /** Why this entry was surfaced — purely for generator prompts / debug. */
  reason: "recently-updated" | "frequently-encountered";
}

/**
 * A line the user has actually translated in the lyric UI. Sourced from
 * the existing `lineAnalysesCache` table keyed by `songId`.
 */
export interface StudyLinePick {
  /** Join key to the analysis caches. Same shape as `stableSongId`. */
  songId: string;
  analysis: AnalysisLine;
  cachedAt: number;
}

/**
 * A song the user has looked up recently (pulled from `songsCache`).
 * Carries enough context for the question prompt to say things like
 * "from 'SongTitle' by ArtistName" without a second query.
 */
export interface StudySongPick {
  /** `${provider}:${externalId}` — same key used by `songsCache`. */
  id: string;
  title: string;
  artist: string;
  provider: string;
  externalId: string;
  cachedAt: number;
}

export interface StudyContext {
  /** Recency-sorted picks from dictionary + analyses + songs. */
  recentDictionary: StudyDictionaryPick[];
  frequentDictionary: StudyDictionaryPick[];
  recentLines: StudyLinePick[];
  recentSongs: StudySongPick[];
  /** Optional direction filter the caller asked for. */
  direction?: DictionaryDirection;
  /** Epoch ms — useful for debug / generator caching. */
  generatedAt: number;
}

// ---------------------------------------------------------------------------
// Popup quiz question — richer than the local QuizQuestion. Lets the LLM
// hand back an explanation + a typed pointer back to the study item.
// ---------------------------------------------------------------------------

export type PopupQuestionKind =
  /** "What does <word> mean?" — prompt=word, answer=meaning. */
  | "word-meaning"
  /** "How is <word> read?" — prompt=word, answer=romaji/reading. */
  | "word-reading"
  /** "What does this lyric line mean?" — prompt=line, answer=translation. */
  | "line-meaning"
  /** "Fill the blank in this line the user just translated." */
  | "fill-blank"
  /** "Which word means <meaning>?" — prompt=meaning, answer=word. */
  | "reverse-meaning";

/**
 * Pointer back to the study material the question came from. Anti-repeat
 * logic dedups on `id`, so prefer stable ids (dictionary entry id, Dexie
 * line cache key).
 */
export interface PopupQuizSourceRef {
  kind: "dictionaryEntry" | "lineAnalysis" | "songAnalysis";
  /**
   * Stable id — dictionary entry id, or a line-cache key of the form
   * `${songId}:${stanzaNumber}:${lineNumber}`.
   */
  id: string;
  /** Optional hints for UI display. */
  surface?: string;
  songTitle?: string;
  artistName?: string;
}

export interface PopupQuizOption {
  text: string;
  isCorrect: boolean;
}

export interface PopupQuizQuestion {
  id: string;
  kind: PopupQuestionKind;
  prompt: string;
  options: PopupQuizOption[];
  /** Denormalised for fast evaluation — always matches `options[i].isCorrect`. */
  correctOptionIndex: number;
  /** Short note on why the correct answer is correct. May be empty. */
  explanation: string;
  source: PopupQuizSourceRef;
  createdAt: number;
}

// ---------------------------------------------------------------------------
// Answer evaluation / reward / history
// ---------------------------------------------------------------------------

export interface PopupQuizAnswerResult {
  correct: boolean;
  correctOptionIndex: number;
  explanation: string;
  question: PopupQuizQuestion;
  /** Currency granted by this answer (0 if wrong). */
  currencyAwarded: number;
}

/**
 * Persisted after each answered question. Used for the UI's recent-history
 * strip and for anti-repeat lookups when building the next prompt.
 */
export interface PopupQuizHistoryEntry {
  id: string;
  kind: PopupQuestionKind;
  /** Stable id of the source material — same as `source.id`. */
  sourceId: string;
  answeredAt: number;
  correct: boolean;
}

// ---------------------------------------------------------------------------
// Generator seam — the future NVIDIA-backed generator plugs in here.
// ---------------------------------------------------------------------------

export interface PopupQuizGeneratorOptions {
  /** Anti-repeat: source ids the caller wants avoided (recently answered). */
  excludeSourceIds?: string[];
  direction?: DictionaryDirection;
}

export interface PopupQuizGenerator {
  /**
   * Build a single popup quiz question from the given study context.
   * Returns null when no question can reasonably be produced (e.g. empty
   * study history on a brand-new user).
   */
  generate(
    context: StudyContext,
    options?: PopupQuizGeneratorOptions
  ): Promise<PopupQuizQuestion | null>;
}
